#!/bin/bash
#  update code folder from git
cd code/
sudo passenger stop
sudo git fetch origin
sudo git reset --hard origin/master
cd ..
sudo chmod -R 777 code/
cd code/
source deactivate
source activate othodi4
python othodi_app.py
sudo passenger start
